### ISSUE TITLE
some of the nodes body are not showing

### ISSUE THREAD

**Issue by xu4wang** [kaleguy/leovue#8] opened 2019-09-05 03:21 UTC
Dear LeoVUE user,

I'm running leovue by putting the dist folder into my www root directory.
Most the the function is working as expected. However, I noticed some of the nodes, especially when the body text is long, are not being displayed on the right side panel.

The left side tree view works fine, I can still see the headline of the notes, but when I click the headline, the right side body panel doesn't change.

I tested with both apache server and python http.server.

Thanks,
Austin

**Comment by xu4wang** [comment] 2019-09-05 04:54
I reproduced the issue with attached leo file.

The body of node "H31" under "PersonalGrown" is not showing.

[issue8.leo.txt](https://github.com/kaleguy/leovue/files/3577482/issue8.leo.txt)

**Comment by xu4wang** [comment] 2019-09-05 05:08
More precise description, node with @language rest directive in the body cannot be displayed.

**Comment by kaleguy** [comment] 2019-09-06 22:01
This was caused by using an unsupported (by highlight.js) language with the @language attribute. Fixed in 2.0.1 by adding an error check. Thanks for the report.

**Closed** 2019-09-09 03:30 UTC
